<?php
/*
 * Generated by CRUDigniter v3.0 Beta
 * www.crudigniter.com
 */

class Riwayat_alamat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get riwayat_alamat by id_riwayat_alamat
     */
    function get_riwayat_alamat($id_riwayat_alamat, $status)
    {
        return $this->db->get_where('riwayat_alamat',array('id_ra'=>$id_riwayat_alamat, 'stts_ra' => $status))->row_array();
    }

    function get_alamat($id_pdk)
    {
      $this->db->select('*');

      $this->db->from('riwayat_alamat');

      $this->db->join('rt', 'riwayat_alamat.id_rt = rt.id_rt');
      $this->db->join('rw', 'rt.id_rw = rw.id_rw');
      $this->db->join('dusun', 'rw.id_dusun = dusun.id_dusun');
      $this->db->join('kelurahan', 'dusun.id_kel = kelurahan.id_kel');
      $this->db->join('kecamatan', 'kelurahan.id_kec = kecamatan.id_kec');
      $this->db->join('kabupaten', 'kecamatan.id_kab = kabupaten.id_kab');
      $this->db->join('provinsi', 'kabupaten.id_prov = provinsi.id_prov');

      $this->db->where('riwayat_alamat.id_pdk', $id_pdk);

      $this->db->where('riwayat_alamat.stts_ra', 'aktif');

      return $this->db->get()->row_array();
    }

    /*
     * Get all riwayat_alamat
     */
    function get_all_riwayat_alamat()
    {
        return $this->db->get('riwayat_alamat')->result_array();
    }

    /*
     * function to add new riwayat_alamat
     */
    function add_riwayat_alamat($params)
    {
        $this->db->insert('riwayat_alamat',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update riwayat_alamat
     */
    function update_riwayat_alamat($id_riwayat_alamat,$params)
    {
        $this->db->where('id_riwayat_alamat',$id_riwayat_alamat);
        $response = $this->db->update('riwayat_alamat',$params);
        if($response)
        {
            return "riwayat_alamat updated successfully";
        }
        else
        {
            return "Error occuring while updating riwayat_alamat";
        }
    }

    /*
     * function to delete riwayat_alamat
     */
    function delete_riwayat_alamat($id_riwayat_alamat)
    {
        $response = $this->db->delete('riwayat_alamat',array('id_riwayat_alamat'=>$id_riwayat_alamat));
        if($response)
        {
            return "riwayat_alamat deleted successfully";
        }
        else
        {
            return "Error occuring while deleting riwayat_alamat";
        }
    }

    public function get_rt_di_rw($id_rw)
    {
      $this->db->select('*');

      $this->db->from('rt');

      $this->db->join('rw', 'rt.id_rw = rw.id_rw');

      $this->db->where('rt.id_rw', $id_rw);

      return $this->db->get()->result_array();
    }

    public function get_kecamatan()
    {
      $this->db->select('*');
      $this->db->from('kecamatan');
      return $this->db->get()->result_array();
    }

    public function get_kelurahan()
    {
      $this->db->select('*');
      $this->db->from('kelurahan');
      return $this->db->get()->result_array();
    }
}
